In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [2]:
categories = np.array([['red'], ['green'], ['blue'], ['green'], ['red']])

encoder = OneHotEncoder(sparse_output=False)

onehot_encoded = encoder.fit_transform(categories)

In [3]:
print('Categories:', encoder.categories_)

print('One-hot encoded array:')
print(onehot_encoded)

Categories: [array(['blue', 'green', 'red'], dtype='<U5')]
One-hot encoded array:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
original_labels = encoder.inverse_transform(onehot_encoded)
print('Recovered original labels:')
print(original_labels)


Recovered original labels:
[['red']
 ['green']
 ['blue']
 ['green']
 ['red']]


In [5]:
raw_data = [['apple'], ['banana'], ['apple'], ['orange']]
encoder2 = OneHotEncoder(sparse_output=False)
encoded_data = encoder2.fit_transform(raw_data)
print('\nRaw data:', raw_data)
print('Categories learned:', encoder2.categories_)
print('One-hot encoded data:')
print(encoded_data)


Raw data: [['apple'], ['banana'], ['apple'], ['orange']]
Categories learned: [array(['apple', 'banana', 'orange'], dtype=object)]
One-hot encoded data:
[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
